CREATE TABLE wtr(
uid integer primary key autoincrement,
"Lic No" TEXT,
"Licensee" TEXT,
"Product" TEXT,
"Publish_Flag" TEXT,
"Trade_Flag" TEXT,
"Issue Date" TEXT,
"lic status" TEXT,
"Latitiude" TEXT,
"Longitude" TEXT,
"NGR" TEXT,
"TX/Rx" TEXT,
"Freq" TEXT,
"Channel_Width" TEXT,
"Height" TEXT,
"Max Radiated Power ERP" TEXT,
"Antenna Type" TEXT,
"Gain" TEXT,
"Azimuth" TEXT,
"An Code H" TEXT,
"An Code V" TEXT,
"Antenna Height" TEXT,
"Antenna Location" TEXT,
"EFL_UPPER_LOWER" TEXT,
"Ant Elevation" TEXT,
"Ant Polarisation" TEXT,
"Antenna Name" TEXT,
"Ant Feeding Loss" TEXT,
"Fade Margin" TEXT,
"EMI Code" TEXT,
"Area Code/Country" TEXT
);
